export const GET_POKEMONS = {
  LOAD: 'MAIN_HOME/GET_POKEMONS_LOAD',
  SUCCESS: 'MAIN_HOME/GET_POKEMONS_SUCCESS',
  FAILURE: 'MAIN_HOME/GET_POKEMONS_FAILURE',
  LOAD_MORE: 'MAIN_HOME/GET_POKEMONS_LOAD_MORE',
  LOAD_MORE_SUCCESS: 'MAIN_HOME/GET_POKEMONS_LOAD_MORE_SUCCESS',
  LOAD_MORE_FAILURE: 'MAIN_HOME/GET_POKEMONS_LOAD_MORE_FAILURE',
};

export const DETAIL_POKEMON = {
  LOAD: 'MAIN_HOME/DETAIL_POKEMON_LOAD',
  SUCCESS: 'MAIN_HOME/DETAIL_POKEMON_SUCCESS',
  FAILURE: 'MAIN_HOME/DETAIL_POKEMON_FAILURE',
};

export const STORE_POKEMONS = {
  STORE: 'MAIN_HOME/STORE_POKEMONS_STORE',
  RESET: 'MAIN_HOME/STORE_POKEMONS_RESET',
};
